/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VISTA;

import MODELOreg.*;
import MODELOobj.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rodri
 */
public class ActaRegistro extends javax.swing.JFrame {

    private registroActas ppa;
    private registroMesasElectorales me;
    private registroCandidatos can;
    private registroElecciones re;
    private eleccion[] eleccionesDisponibles;

    private DefaultTableModel datos;
    private DefaultTableModel candidatos;

    private ActaRegistro() {

        initComponents();
            this.setLocationRelativeTo(null);
        
    }

    public ActaRegistro(registroActas pp, registroMesasElectorales me, registroCandidatos can, registroElecciones re) {
        initComponents();
            this.setLocationRelativeTo(null);
        ppa = pp;
        this.me = me;
        this.can = can;
        this.re = re;
        eleccionesDisponibles = new eleccion[re.longitud()];

        cmbMesa.removeAllItems();
        cmbEleccion.removeAllItems();

        for (int i = 0; i < me.longitud(); i++) {
            mesaElectoral m = me.iesimo(i);
            cmbMesa.addItem(m.getIdMesa());
        }

        for (int i = 0; i < re.longitud(); i++) {
            eleccion e = re.iesimo(i);
            eleccionesDisponibles[i] = e;
            cmbEleccion.addItem(e.toString());
        }
        if (cmbEleccion.getItemCount() > 0) {
            cmbEleccion.setSelectedIndex(0);
            cmbEleccionActionPerformed(null);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNumeroActa = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        txtTituloActa = new javax.swing.JTextField();
        btnCerrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtLugar = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cmbMesa = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtVotosNulos = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtVotosRegistrados = new javax.swing.JTextField();
        txtVotosBlancos = new javax.swing.JTextField();
        txtVotosEfectivos = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taDatos = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservaciones = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        txtHora = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        taDatos2 = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        chkSello = new javax.swing.JCheckBox();
        cmbEleccion = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Numero Acta :");

        jLabel3.setText("Titulo Acta :");

        jLabel4.setText("Fecha :");

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        jLabel5.setText("Lugar : ");

        jLabel6.setText("ID de Mesa :");

        btnRegistrar.setText("Registrar Acta ");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel7.setText("Formulario de Registro");

        cmbMesa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMesaActionPerformed(evt);
            }
        });

        jLabel2.setText("Miembros de Mesa :");

        jLabel8.setText("Nro. Votos Efectivos :");

        jLabel9.setText("Nro. Votos Registrados :");

        jLabel10.setText("Nro. Votos Blancos :");

        txtVotosBlancos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVotosBlancosActionPerformed(evt);
            }
        });

        jLabel11.setText("Nro. Votos Nulos :");

        jLabel13.setText("Observaciones :");

        taDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(taDatos);

        txtObservaciones.setColumns(20);
        txtObservaciones.setRows(5);
        jScrollPane1.setViewportView(txtObservaciones);

        jLabel12.setText("Hora :");

        taDatos2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(taDatos2);

        jLabel14.setText("Votos Preferenciales:");

        jLabel15.setText("Cuenta con Sello Oficial :");

        cmbEleccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbEleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEleccionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbEleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(192, 192, 192)
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtVotosRegistrados, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel11)
                                                    .addComponent(jLabel10))
                                                .addGap(7, 7, 7)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(26, 26, 26)
                                                        .addComponent(txtVotosNulos, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(txtVotosBlancos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel9)
                                                    .addComponent(jLabel8))
                                                .addGap(33, 33, 33)
                                                .addComponent(txtVotosEfectivos, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(2, 2, 2))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(161, 161, 161)
                                            .addComponent(txtNumeroActa, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel5)
                                                    .addComponent(jLabel12))
                                                .addGap(26, 26, 26)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(28, 28, 28)
                                                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(56, 56, 56)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel3))
                                        .addGap(28, 28, 28)
                                        .addComponent(txtTituloActa, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(81, 81, 81)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmbMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel2)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel14)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(151, 151, 151)
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(chkSello)
                                .addGap(80, 80, 80)
                                .addComponent(btnRegistrar)))
                        .addContainerGap(50, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(415, 415, 415)
                .addComponent(btnCerrar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbEleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(cmbMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNumeroActa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtTituloActa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(txtLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtVotosRegistrados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtVotosEfectivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtVotosBlancos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtVotosNulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(chkSello))
                        .addGap(53, 53, 53)
                        .addComponent(btnCerrar)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnRegistrar)
                        .addGap(103, 103, 103))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed

        String numeroActa = this.txtNumeroActa.getText();
        String titulo = this.txtTituloActa.getText();
        String fecha = this.txtFecha.getText();
        String hora = this.txtHora.getText();
        String lugar = this.txtLugar.getText();

        //2
        String idMesa = this.cmbMesa.getSelectedItem().toString();
        mesaElectoral mesa = me.buscarID(idMesa);
        miembroMesa[] miembros = mesa.getMiembros();

        String[] miembrosNombres = new String[miembros.length];
        String firmas = "";
        int firmaron = 0;

        for (int i = 0; i < taDatos.getRowCount(); i++) {
            String nombre = taDatos.getValueAt(i, 0).toString();
            miembrosNombres[i] = nombre;

            boolean firmo = (boolean) taDatos.getValueAt(i, 2);
            if (firmo) {
                firmas += nombre + "  ";
                firmaron++;
            }
        }

        if (firmaron < miembros.length) {
            JOptionPane.showMessageDialog(rootPane, "No todos los miembros firmaron el Acta");
        }

        int registrados = Integer.parseInt(txtVotosRegistrados.getText().trim());
        int efectivos = Integer.parseInt(txtVotosEfectivos.getText().trim());
        int blancos = Integer.parseInt(txtVotosBlancos.getText().trim());
        int nulos = Integer.parseInt(txtVotosNulos.getText().trim());

        int totalCandidatos = 0;
        for (int i = 0; i < taDatos2.getRowCount(); i++) {
            int v = Integer.parseInt(taDatos2.getValueAt(i, 2).toString().trim());
            totalCandidatos += v;
        }

        if (totalCandidatos != efectivos) {
            JOptionPane.showMessageDialog(this, "La suma de votos no coincide con los votos efectivos.");
            return;
        }

        if (efectivos > registrados) {
            JOptionPane.showMessageDialog(this, "Los votos efectivos no pueden ser mayores que los registrados.");
            return;
        }
        if ((efectivos + blancos + nulos) != registrados) {
            JOptionPane.showMessageDialog(this, "La suma de votos no coinciden con los registrados.");
            return;
        }

        int filas = taDatos2.getRowCount();
        candidato[] candidatos = new candidato[filas];
        int[] votos = new int[filas];

        for (int i = 0; i < filas; i++) {
            String nombre = taDatos2.getValueAt(i, 0).toString();
            String partido = taDatos2.getValueAt(i, 1).toString();
            String votoTexto = taDatos2.getValueAt(i, 2).toString().trim();

            int voto = Integer.parseInt(votoTexto);
            candidatos[i] = new candidato(nombre, "", "", partido);
            votos[i] = voto;
        }

        String observaciones = txtObservaciones.getText().trim();

        boolean tieneSello = chkSello.isSelected();
        eleccion seleccionada = eleccionesDisponibles[cmbEleccion.getSelectedIndex()];
        int indice = cmbEleccion.getSelectedIndex();
        eleccion eleccionSeleccionada = eleccionesDisponibles[indice];

        actaElectoral nueva = new actaElectoral(
                numeroActa, titulo, fecha, hora, lugar,
                idMesa, miembrosNombres,
                registrados, efectivos,
                blancos, nulos,
                candidatos, votos,
                observaciones, firmas,
                tieneSello,seleccionada
        );

        eleccionSeleccionada.agregarActa(nueva);
        ppa.agregar(nueva); // opcional

        JOptionPane.showMessageDialog(rootPane, "Acta registrada correctamente.");

        txtNumeroActa.setText("");
        txtTituloActa.setText("");
        txtFecha.setText("");
        txtHora.setText("");
        txtLugar.setText("");
        txtVotosRegistrados.setText("");
        txtVotosEfectivos.setText("");
        txtVotosBlancos.setText("");
        txtVotosNulos.setText("");
        txtObservaciones.setText("");
        chkSello.setSelected(false);

        for (int i = 0; i < taDatos2.getRowCount(); i++) {
            taDatos2.setValueAt("0", i, 2);
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void cmbMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMesaActionPerformed
        datos = new DefaultTableModel() {

            @Override
            public boolean isCellEditable(int row, int column) {
                return column == 2;
            }

            @Override
            public Class getColumnClass(int column) {
                if (column == 2) {
                    return Boolean.class;
                } else {
                    return String.class;
                }
            }

        };
        datos.addColumn("Nombre");
        datos.addColumn("Tipo");
        datos.addColumn("Firmo?");

        String idMesa = (String) cmbMesa.getSelectedItem();
        for (int i = 0; i < me.longitud(); i++) {
            if (me.longitud() <= 0) {
                JOptionPane.showMessageDialog(rootPane, "Necesita tener Mesas Electorales Registradas");
            }
            mesaElectoral m = me.iesimo(i);
            if (m.getIdMesa().equals(idMesa)) {
                miembroMesa[] miembros = m.getMiembros();
                for (int j = 0; j < miembros.length; j++) {
                    Object[] fila = new Object[3];
                    fila[0] = miembros[j].getNombreCompleto();
                    fila[1] = miembros[j].getTipo();
                    fila[2] = false;
                    datos.addRow(fila);
                }

            }

        }

        this.taDatos.setModel(datos);

    }//GEN-LAST:event_cmbMesaActionPerformed

    private void cmbEleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEleccionActionPerformed

        int indice = cmbEleccion.getSelectedIndex();
        if (indice == -1 || eleccionesDisponibles[indice] == null) {
            return;
        }
        eleccion seleccionada = eleccionesDisponibles[indice];

        candidato[] candidatosAsociados = seleccionada.getCandidatos();

        DefaultTableModel modelo = new DefaultTableModel() {

            @Override
            public boolean isCellEditable(int row, int column) {
                return column == 2;
            }
        };

        modelo.addColumn("Candidato");
        modelo.addColumn("Partido");
        modelo.addColumn("Votos");

        for (int i = 0; i < candidatosAsociados.length; i++) {
            Object[] fila = new Object[3];
            fila[0] = candidatosAsociados[i].getNombreCompleto();
            fila[1] = candidatosAsociados[i].getPartidoPolitico();
            fila[2] = "0";
            modelo.addRow(fila);
        }

        taDatos2.setModel(modelo);
    }//GEN-LAST:event_cmbEleccionActionPerformed

    private void txtVotosBlancosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVotosBlancosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVotosBlancosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActaRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JCheckBox chkSello;
    private javax.swing.JComboBox<String> cmbEleccion;
    private javax.swing.JComboBox<String> cmbMesa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable taDatos;
    private javax.swing.JTable taDatos2;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtLugar;
    private javax.swing.JTextField txtNumeroActa;
    private javax.swing.JTextArea txtObservaciones;
    private javax.swing.JTextField txtTituloActa;
    private javax.swing.JTextField txtVotosBlancos;
    private javax.swing.JTextField txtVotosEfectivos;
    private javax.swing.JTextField txtVotosNulos;
    private javax.swing.JTextField txtVotosRegistrados;
    // End of variables declaration//GEN-END:variables
}
